
```{r}
library(tibble)
library(ggplot2)
```


```{r}
boundary_df <- tribble(
  ~id,    ~long,  ~lat,
  # Row 1: Cell (1,1)
  "c11",   0,   0,
  "c11",  10,   0,
  "c11",  10,  10,
  "c11",   0,  10,
  
  # Row 1: Cell (1,2)
  "c12",  10,   0,
  "c12",  20,   0,
  "c12",  20,  10,
  "c12",  10,  10,
  
  # Row 1: Cell (1,3)
  "c13",  20,   0,
  "c13",  30,   0,
  "c13",  30,  10,
  "c13",  20,  10,
  
  # Row 2: Cell (2,1)
  "c21",   0,  10,
  "c21",  10,  10,
  "c21",  10,  20,
  "c21",   0,  20,
  
  # Row 2: Cell (2,2)
  "c22",  10,  10,
  "c22",  20,  10,
  "c22",  20,  20,
  "c22",  10,  20,
  
  # Row 2: Cell (2,3)
  "c23",  20,  10,
  "c23",  30,  10,
  "c23",  30,  20,
  "c23",  20,  20,
  
  # Row 3: Cell (3,1)
  "c31",   0,  20,
  "c31",  10,  20,
  "c31",  10,  30,
  "c31",   0,  30,
  
  # Row 3: Cell (3,2)
  "c32",  10,  20,
  "c32",  20,  20,
  "c32",  20,  30,
  "c32",  10,  30,
  
  # Row 3: Cell (3,3)
  "c33",  20,  20,
  "c33",  30,  20,
  "c33",  30,  30,
  "c33",  20,  30
)
boundary_df
```



```{r}
centers_df <- tribble(
  ~id,   ~long, ~lat,
  "c11",    5,     5,
  "c12",   15,     5,
  "c13",   25,     5,
  "c21",    5,    15,
  "c22",   15,    15,
  "c23",   25,    15,
  "c31",    5,    25,
  "c32",   15,    25,
  "c33",   25,    25
)
centers_df
```


```{r}
ggplot() +
  geom_map(
    data = values_df,
    map = boundary_df,
    aes(map_id = id, fill = value)
  ) +
  expand_limits(x = boundary_df$long, y = boundary_df$lat)
```


```{r}
values_df <- tribble(
  ~id,    ~value,
  "c11",  1,
  "c12",  2,
  "c13",  3,
  "c21",  3,
  "c22",  5,
  "c23",  6,
  "c31",  7,
  "c32",  8,
  "c33",  9
)
values_df
```

```{r}
ggplot() +
  geom_map(
    data = values_df,
    map = boundary_df,
    aes(map_id = id, fill = value)
  ) +
  geom_point(
    data = centers_df,
    aes(x = long, y = lat)
  ) +
  expand_limits(x = boundary_df$long, y = boundary_df$lat)
```